apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "carla-scheduler.fullname" . }}-config
  labels:
    {{- include "carla-scheduler.labels" . | nindent 4 }}
data:
  carla_policy.yaml: |
{{ (.Files.Get "configs/carla_policy.yaml") | indent 4 }}
  apps.yaml: |
{{ (.Files.Get "configs/apps.yaml") | indent 4 }}
