apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/name: {{ include "onco-app.fullname" . }}-backend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ include "onco-app.fullname" . }}-backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    protocol: TCP
