# To see all available options, please visit the docs:
# https://docs.fossorial.io/Pangolin/Configuration/config

app:
    dashboard_url: "https://pangolin.<domain>"
    log_level: "info"
    save_logs: true

domains:
    domain1:
        base_domain: "<domain>"
        cert_resolver: "letsencrypt"

server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: "pangolin"
    session_cookie_name: "p_session_token"
    resource_access_token_param: "p_token"
    resource_access_token_headers:
        id: "P-Access-Token-Id"
        token: "P-Access-Token"
    resource_session_request_param: "p_session_request"
    secret: <secret>
    cors:
        origins: ["https://pangolin.<domain>"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

traefik:
    cert_resolver: "letsencrypt"
    http_entrypoint: "web"
    https_entrypoint: "websecure"

gerbil:
    start_port: 51820
    base_endpoint: "pangolin.<domain>"
    use_subdomain: false
    block_size: 24
    site_block_size: 30
    subnet_group: <subnet_range>
    ports:
      - 51820:51820/udp # LEAVE ALONE: For Wireguard
      - 443:443 # LEAVE ALONE: For HTTPS
      - 80:80 # LEAVE ALONE: For HTTP
      - 2222:2222
      - 8083:8080

rate_limits:
    global:
        window_minutes: 1
        max_requests: 500

users:
    server_admin:
        email: "<admin_email>"
        password: "<admin_password>"

flags:
    require_email_verification: false
    disable_signup_without_invite: true
    disable_user_create_org: false
    allow_raw_resources: true
    allow_base_domain_resources: true
