# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: fabian2001/licenta-backend:latest
        env:
        - name: MONGO_CONNECTION_STRING
          value: <value from secret>
        - name: PORT
          value: "5000"
        - name: SESSION_SECRET
          value: <value from secret>
        ports:
        - containerPort: 5000
