# Registry of Applications for CARLA.
# r_i: resource proxy (cpu_cores + 0.1 * mem_GiB)
# d_i: dependency depth (e.g., sync wave; 0 = earliest)
# risk: 0=low, 1=medium, 2=high (e.g., ingress, security, storage)
# window_fit: optional override per-app (0/1); if omitted, computed from current time window.

apps:
  - name: "mgmt/metallb"
    r_i: 1.0
    d_i: 0
    risk: 0
    toggleRevisions: ["revA", "revB"]

  - name: "mgmt/k8s-monitoring"    # Grafana Alloy Operator / collectors
    r_i: 2.0
    d_i: 1
    risk: 1
    toggleRevisions: ["revA", "revB"]

  - name: "mgmt/lgtm-distributed"  # Loki+Mimir+Tempo+Pyroscope umbrella
    r_i: 4.5
    d_i: 2
    risk: 1
    toggleRevisions: ["revA", "revB"]

  - name: "apps/onco-app"          # your biomedical workload
    r_i: 3.0
    d_i: 2
    risk: 1
    toggleRevisions: ["revA", "revB"]

  - name: "edge/ingress"           # Traefik / gateway layer
    r_i: 1.5
    d_i: 1
    risk: 2
    toggleRevisions: ["revA", "revB"]

  - name: "mgmt/argocd-plugins"    # optional tiny mgmt app
    r_i: 1.0
    d_i: 0
    risk: 0
    toggleRevisions: ["revA", "revB"]

defaults:
  # If an app misses a field, these are used.
  r_i: 1.5
  d_i: 1
  risk: 1

notes:
  # Set toggleRevisions to two real revisions (tags/commits/branches) per app
  # that are safe to alternate so CARLA can force a sync during experiments.
  # Depth values should reflect your app-of-apps / sync-wave ordering.
  # Tune r_i using requests/limits or observed mean usage (cpu + 0.1*GiB).
